### ISSUE TITLE
我参考了您的v1.0写了一份文档，关于参考文献

### ISSUE THREAD

**Issue by lingr7** [JingXuan-Yang/YangTemplate#1]
您的《人工智能》课程论文里bibitem是按照在文章中引用号出现的顺序手动打进去和排序的吗？
首先是改造使用Bib文件来引入参考文献的问题，我自己尝试用zotero导出的Bib直接插入失败以后，就用Latex中使用bib文件批量生成bbl格式文件 - JSJWR的博客 - CSDN博客  https://blog.csdn.net/JSJWR/article/details/79373900?utm_source=blogxgwz7 生成了bbl文件，但是顺序还是要自己手动调整。53条文献手动？这也太累了吧，用了什么方法来调整顺序为在文中出现的顺序呢？

**Comment by Jingxuan-Yang** [comment]
我的模板中参考文献是按照正文出现顺序打进去的，若要自动按照正文出现顺序排列，使用bib就可以做到引用哪些文献就输出哪些文献，并且按照正文出现顺序，我不清楚你为何还需要手动调整。具体可以参考其他人写的硕博毕业论文模板，他们的参考文献非常多，肯定是采取自动排序的方式处理的。我这篇论文参考文献很少，故采取手动方式。

**Comment by lingr7** [comment]
> [vscode的配置文件setting.json的UI界面或者json形式 - Gabriel_wei的博客 - CSDN博客](https://blog.csdn.net/Gabriel_wei/article/details/90437487) 


>[ Mac下vscode latex-workshop新的配置文件 - 知乎](  https://zhuanlan.zhihu.com/p/35473874)  

我使用的插件，编译的时候，没有把参考文献加入编译过程，bibtex要生效，需要xelatex->bibtex->xelatex->xelatex 才能生效，生成参考文献，之前就是这个问题导致我直接引入bib，但生成参考文献失败。
配置如下，方能成功。 mac和win10一样
```
  "latex-workshop.latex.recipes": [
        {
          "name": "xelatex",
          "tools": [
            "xelatex"
          ]
        },
        {
          "name": "xelatex -> bibtex -> xelatex*2",
          "tools": [
            "xelatex",
            "bibtex",
            "xelatex",
            "xelatex"
          ]
        }
      ],
      "latex-workshop.latex.tools": [
        {
          "name": "latexmk",
          "command": "latexmk",
          "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-pdf",
            "%DOC%"
          ]
        },
        {
          "name": "xelatex",
          "command": "xelatex",
          "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "%DOC%"
          ]
        },
        {
          "name": "bibtex",
          "command": "bibtex",
          "args": [
            "%DOCFILE%"
          ]
        }
      ],
      "latex-preview.command": "xelatex"
```

**Comment by Jingxuan-Yang** [comment]
我是使用TexStudio编写tex文件的，该软件可以自动完成全部的编译过程

**Comment by lingr7** [comment]
我折腾很久没有搞出参考文献，于是装了TexStudio试了一下，发现这一点后调整了。您可以把这个issue关闭了，问题解决了。
